- name: install nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: start and enable nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: remove html directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: create html directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: download web artifact
  ansible.builtin.get_url:
    url: https://roboshop-builds.s3.amazonaws.com/web.zip
    dest: /tmp

- name: extract web artifact
  ansible.builtin.unarchive:
    src: /tmp/web.zip
    dest: /usr/share/nginx/html
    remote_src: yes

# when it is checking template by default it will go to template folder and it will get the roboshop.conf
# and it will place in default.d
# When this configuration is changing then this task will notify to restart nginx
- name: copy roboshop.conf
  ansible.builtin.template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf
  notify:
  - restart nginx

